# Setup
title:               Psieniądze
tagline:             'Bardzo, bardzo psieniądze'
description:         'Pierwszy psiestanek na drodze do oświecenia'
url:                 https://www.xn--psienidze-gdb.pl
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Atos
  url:               https://www.xn--psienidze-gdb.pl
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id:
